# Generated by Django 5.1.6 on 2025-03-12 09:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificator', models.CharField(max_length=50, verbose_name='Идентификатор')),
                ('cycles', models.CharField(max_length=255, verbose_name='Название цикла')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Дисциплина')),
            ],
            options={
                'verbose_name': 'Модуль',
                'verbose_name_plural': 'Модули',
            },
        ),
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization_code', models.CharField(max_length=50, verbose_name='Шифр специальности')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('create_date', models.DateField(verbose_name='Дата документа')),
                ('gos_type', models.CharField(max_length=50, verbose_name='Тип ГОС')),
            ],
            options={
                'verbose_name': 'Учебный план',
                'verbose_name_plural': 'Учебные планы',
            },
        ),
        migrations.CreateModel(
            name='Disipline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Дисциплина')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_plan_strings', to='parserapp.module', verbose_name='Модуль')),
            ],
            options={
                'verbose_name': 'Дисциплина',
                'verbose_name_plural': 'Дисциплины',
            },
        ),
        migrations.CreateModel(
            name='StudyCycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificator', models.CharField(max_length=50, verbose_name='Идентификатор')),
                ('cycles', models.CharField(max_length=255, verbose_name='Название дочернего цикла')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_cycles', to='parserapp.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Учебный цикл',
                'verbose_name_plural': 'Учебные циклы',
            },
        ),
        migrations.AddField(
            model_name='module',
            name='studey_cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_strings', to='parserapp.studycycle', verbose_name='Учебный цикл'),
        ),
        migrations.CreateModel(
            name='ClockCell',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_of_type_work', models.IntegerField(blank=True, null=True, verbose_name='Код вида работы')),
                ('code_of_type_hours', models.IntegerField(blank=True, null=True, verbose_name='Код типа часов')),
                ('course', models.IntegerField(blank=True, null=True, verbose_name='Курс')),
                ('semestr', models.IntegerField(blank=True, null=True, verbose_name='Семестр')),
                ('count_of_clocks', models.IntegerField(blank=True, null=True, verbose_name='Количество часов')),
                ('plan_string', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clock_cells', to='parserapp.disipline', verbose_name='План строки')),
                ('child_plan_string', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clock_cells', to='parserapp.studycycle', verbose_name='Дочерний план строки')),
            ],
            options={
                'verbose_name': 'Ячейка часов',
                'verbose_name_plural': 'Ячейки часов',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='study_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='parserapp.studyplan', verbose_name='Учебный план'),
        ),
    ]
