# Generated by Django 5.1.6 on 2025-03-09 09:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChildPlanString',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.CharField(max_length=255, verbose_name='Дисциплина')),
            ],
            options={
                'verbose_name': 'Дочерний план строки',
                'verbose_name_plural': 'Дочерние планы строк',
            },
        ),
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificator', models.CharField(max_length=50, verbose_name='Идентификатор')),
                ('cycles', models.CharField(max_length=255, verbose_name='Название цикла')),
            ],
            options={
                'verbose_name': 'Цикл',
                'verbose_name_plural': 'Циклы',
            },
        ),
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization_code', models.CharField(max_length=50, verbose_name='Шифр специальности')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('create_date', models.DateField(verbose_name='Дата документа')),
                ('gos_type', models.CharField(max_length=50, verbose_name='Тип ГОС')),
            ],
            options={
                'verbose_name': 'Учебный план',
                'verbose_name_plural': 'Учебные планы',
            },
        ),
        migrations.CreateModel(
            name='ChildCycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificator', models.CharField(max_length=50, verbose_name='Идентификатор')),
                ('cycles', models.CharField(max_length=255, verbose_name='Название дочернего цикла')),
                ('parent_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_cycles', to='parserapp.cycle', verbose_name='Родительский цикл')),
            ],
            options={
                'verbose_name': 'Дочерний цикл',
                'verbose_name_plural': 'Дочерние циклы',
            },
        ),
        migrations.CreateModel(
            name='PlanString',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.CharField(max_length=255, verbose_name='Дисциплина')),
                ('child_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_strings', to='parserapp.childcycle', verbose_name='Дочерний цикл (блок)')),
            ],
            options={
                'verbose_name': 'План строки',
                'verbose_name_plural': 'Планы строк',
            },
        ),
        migrations.CreateModel(
            name='ClockCell',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_of_type_work', models.IntegerField(blank=True, null=True, verbose_name='Код вида работы')),
                ('code_of_type_hours', models.IntegerField(blank=True, null=True, verbose_name='Код типа часов')),
                ('course', models.IntegerField(blank=True, null=True, verbose_name='Курс')),
                ('semestr', models.IntegerField(blank=True, null=True, verbose_name='Семестр')),
                ('count_of_clocks', models.IntegerField(blank=True, null=True, verbose_name='Количество часов')),
                ('child_plan_string', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clock_cells', to='parserapp.childplanstring', verbose_name='Дочерний план строки')),
                ('plan_string', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clock_cells', to='parserapp.planstring', verbose_name='План строки')),
            ],
            options={
                'verbose_name': 'Ячейка часов',
                'verbose_name_plural': 'Ячейки часов',
            },
        ),
        migrations.AddField(
            model_name='childplanstring',
            name='parent_plan_string',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_plan_strings', to='parserapp.planstring', verbose_name='Родительский план строки'),
        ),
        migrations.AddField(
            model_name='cycle',
            name='study_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='parserapp.studyplan', verbose_name='Учебный план'),
        ),
    ]
