# Generated by Django 5.1.6 on 2025-03-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parserapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='warning',
            field=models.BooleanField(default=False, verbose_name='Наличие предупреждения'),
        ),
        migrations.AddField(
            model_name='category',
            name='warning_description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание предупреждения'),
        ),
        migrations.AddField(
            model_name='clockcell',
            name='warning',
            field=models.BooleanField(default=False, verbose_name='Наличие предупреждения'),
        ),
        migrations.AddField(
            model_name='clockcell',
            name='warning_description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание предупреждения'),
        ),
        migrations.AddField(
            model_name='disipline',
            name='warning',
            field=models.BooleanField(default=False, verbose_name='Наличие предупреждения'),
        ),
        migrations.AddField(
            model_name='disipline',
            name='warning_description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание предупреждения'),
        ),
        migrations.AddField(
            model_name='module',
            name='warning',
            field=models.BooleanField(default=False, verbose_name='Наличие предупреждения'),
        ),
        migrations.AddField(
            model_name='module',
            name='warning_description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание предупреждения'),
        ),
        migrations.AddField(
            model_name='studycycle',
            name='warning',
            field=models.BooleanField(default=False, verbose_name='Наличие предупреждения'),
        ),
        migrations.AddField(
            model_name='studycycle',
            name='warning_description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание предупреждения'),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='warning',
            field=models.BooleanField(default=False, verbose_name='Наличие предупреждения'),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='warning_description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание предупреждения'),
        ),
    ]
