# Generated by Django 5.1.6 on 2025-03-12 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parserapp', '0005_remove_category_warning_remove_clockcell_warning_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhitelistWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='clockcell',
            options={},
        ),
        migrations.AlterModelOptions(
            name='disipline',
            options={},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={},
        ),
        migrations.AlterModelOptions(
            name='studycycle',
            options={},
        ),
        migrations.AlterModelOptions(
            name='studyplan',
            options={},
        ),
        migrations.RemoveField(
            model_name='clockcell',
            name='warning_description',
        ),
        migrations.RemoveField(
            model_name='clockcell',
            name='warnings',
        ),
        migrations.AlterField(
            model_name='category',
            name='cycles',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='identificator',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='study_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='parserapp.studyplan'),
        ),
        migrations.AlterField(
            model_name='category',
            name='warning_description',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='warnings',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clockcell',
            name='child_plan_string',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clock_cells', to='parserapp.studycycle'),
        ),
        migrations.AlterField(
            model_name='clockcell',
            name='code_of_type_hours',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clockcell',
            name='code_of_type_work',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clockcell',
            name='count_of_clocks',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='clockcell',
            name='course',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='clockcell',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='clockcell',
            name='plan_string',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clock_cells', to='parserapp.disipline'),
        ),
        migrations.AlterField(
            model_name='clockcell',
            name='semestr',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='disipline',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='disipline',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_plan_strings', to='parserapp.module'),
        ),
        migrations.AlterField(
            model_name='disipline',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='disipline',
            name='warning_description',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='disipline',
            name='warnings',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='module',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='studey_cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_strings', to='parserapp.studycycle'),
        ),
        migrations.AlterField(
            model_name='module',
            name='warning_description',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='warnings',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studycycle',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_cycles', to='parserapp.category'),
        ),
        migrations.AlterField(
            model_name='studycycle',
            name='cycles',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studycycle',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studycycle',
            name='identificator',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studycycle',
            name='warning_description',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studycycle',
            name='warnings',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='create_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='gos_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='specialization_code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='warning_description',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='warnings',
            field=models.BooleanField(default=False),
        ),
    ]
