# Generated by Django 5.1.6 on 2025-03-12 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parserapp', '0006_whitelistword_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disipline',
            name='index',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
