# Generated by Django 5.1.6 on 2025-03-13 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parserapp', '0007_disipline_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clockcell',
            name='child_plan_string',
        ),
        migrations.AddField(
            model_name='clockcell',
            name='module_plan_string',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clock_cells', to='parserapp.module'),
        ),
    ]
