# Generated by Django 5.1.6 on 2025-03-13 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parserapp', '0008_remove_clockcell_child_plan_string_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studyplan',
            old_name='gos_type',
            new_name='admission_year',
        ),
        migrations.RenameField(
            model_name='studyplan',
            old_name='name',
            new_name='qualification',
        ),
        migrations.RemoveField(
            model_name='studyplan',
            name='specialization_code',
        ),
    ]
